homepage_url: "https://mrcraftteammc.github.io/HorizontalNekoPlugin"
update_url: "https://mrcraftteammc.github.io/HorizontalNekoPlugin/version-list.json"
issues_url: "https://github.com/MrCraftTeamMC/HorizontalNekoPlugin/issues"
wiki_url: "https://github.com/MrCraftTeamMC/HorizontalNekoPlugin/wiki"

lang:
  
